### ISSUE TITLE
Alpha build 0.1.0 hangs under QEMU

### ISSUE THREAD

**Issue by Kry-a** [LemonOSProject/LemonOS#1]
### What happens?
It just completely hangs at the boot screen, roughly at what I assume is the progress bar middle point.

I _have_ tried running it under no forced graphics mode, same result, just different resolution.

### Notes
I've noticed it gets stuck using 100% CPU
And it completely stops using the disk after getting stuck, resulting in 0 KiB/s reads and writes.

### Screenshot
![image](https://user-images.githubusercontent.com/46050962/85956706-fdd65280-b95d-11ea-895d-4c92008ef7c2.png)

**Comment by fido2020** [comment]
Thanks for opening an issue, I believe that there is an issue with the IDE/ATA driver on QEMU where it hangs. Try running it with the -M q35 option which will default to using AHCI.

**Comment by fido2020** [comment]
I will look into it further when I get the chance

**Comment by Kry-a** [comment]
Yep, it was exactly that, sorry for the problem.
