### ISSUE TITLE
Information...

### ISSUE THREAD

**Issue by pgmrDohan** [LemonOSProject/LemonOS#19]
I want to add the Wi-Fi connection function and the web browser application to my own operating system. but I can't find the Wi-Fi connection function information on the "wiki.osdev" site, so I'd like to know where you got the related data.

**Comment by fido2020** [comment]
Please ask any questions like that in the OSDev Forums, Discord, subreddit, etc. or at the very least contact me via email as this has nothing to do with Lemon OS. Also it is clear you have hardly looked into this project as it has no Wi-Fi support and I am not aware of any small/hobby OSes that do.
