### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by nexos-dev** [LemonOSProject/LemonOS#2]
Hello,
This is a great project! Probably one of the best hobby OSes out there. I was wondering how you build this OS.
Thanks a lot.

**Comment by fido2020** [comment]
The build process is fairly convoluted right now, you need to build the toolchain with ./buildtoolchain.sh - first binutils then gcc. You then have to configure mlibc with meson and build mlibc before building libstdc++ and then finally freetype, zlib and libpng with buildport then LibLemon, the applications, the kernel and finally the disk, which can be done with the build script. I definitely need an easier configuration and build process which I will definitely get around to soon.

**Comment by nexos-dev** [comment]
Ok Thank you!

**Comment by fido2020** [comment]
I added a [build instructions page on the wiki](https://github.com/fido2020/Lemon-OS/wiki/Building-Lemon-OS) let me know if you have any problems
