### ISSUE TITLE
lemon-clang: not found

### ISSUE THREAD

**Issue by erm100** [LemonOSProject/LemonOS#23]
Hello

**Environment:**
Ubuntu 20.04.2 LTS 
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
meson 0.58.1

**Command sequence:**
> cd Toolchain
JOBCOUNT=12 LINKCOUNT=4 ./buildtoolchain.sh build
cd ..
cd Scripts
./configure.sh
cd ..
cd Build
ninja install

**Result:**
> ~/LemonOS/Build$ ninja install
[1/226] Compiling C object subprojects/lai/liblai.a.p/core_error.c.o
FAILED: subprojects/lai/liblai.a.p/core_error.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_error.c.o -MF subprojects/lai/liblai.a.p/core_error.c.o.d -o subprojects/lai/liblai.a.p/core_error.c.o -c ../subprojects/lai/core/error.c
/bin/sh: 1: lemon-clang: not found
[2/226] Compiling C object subprojects/lai/liblai.a.p/core_eval.c.o
FAILED: subprojects/lai/liblai.a.p/core_eval.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_eval.c.o -MF subprojects/lai/liblai.a.p/core_eval.c.o.d -o subprojects/lai/liblai.a.p/core_eval.c.o -c ../subprojects/lai/core/eval.c
/bin/sh: 1: lemon-clang: not found
[3/226] Compiling C object subprojects/lai/liblai.a.p/core_exec.c.o
FAILED: subprojects/lai/liblai.a.p/core_exec.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_exec.c.o -MF subprojects/lai/liblai.a.p/core_exec.c.o.d -o subprojects/lai/liblai.a.p/core_exec.c.o -c ../subprojects/lai/core/exec.c
/bin/sh: 1: lemon-clang: not found
[4/226] Compiling C object subprojects/lai/liblai.a.p/core_exec-operand.c.o
FAILED: subprojects/lai/liblai.a.p/core_exec-operand.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_exec-operand.c.o -MF subprojects/lai/liblai.a.p/core_exec-operand.c.o.d -o subprojects/lai/liblai.a.p/core_exec-operand.c.o -c ../subprojects/lai/core/exec-operand.c
/bin/sh: 1: lemon-clang: not found
[5/226] Compiling C object subprojects/lai/liblai.a.p/core_libc.c.o
FAILED: subprojects/lai/liblai.a.p/core_libc.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_libc.c.o -MF subprojects/lai/liblai.a.p/core_libc.c.o.d -o subprojects/lai/liblai.a.p/core_libc.c.o -c ../subprojects/lai/core/libc.c
/bin/sh: 1: lemon-clang: not found
[6/226] Compiling C object subprojects/lai/liblai.a.p/core_ns.c.o
FAILED: subprojects/lai/liblai.a.p/core_ns.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_ns.c.o -MF subprojects/lai/liblai.a.p/core_ns.c.o.d -o subprojects/lai/liblai.a.p/core_ns.c.o -c ../subprojects/lai/core/ns.c
/bin/sh: 1: lemon-clang: not found
[7/226] Compiling C object subprojects/lai/liblai.a.p/core_object.c.o
FAILED: subprojects/lai/liblai.a.p/core_object.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_object.c.o -MF subprojects/lai/liblai.a.p/core_object.c.o.d -o subprojects/lai/liblai.a.p/core_object.c.o -c ../subprojects/lai/core/object.c
/bin/sh: 1: lemon-clang: not found
[8/226] Compiling C object subprojects/lai/liblai.a.p/core_opregion.c.o
FAILED: subprojects/lai/liblai.a.p/core_opregion.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_opregion.c.o -MF subprojects/lai/liblai.a.p/core_opregion.c.o.d -o subprojects/lai/liblai.a.p/core_opregion.c.o -c ../subprojects/lai/core/opregion.c
/bin/sh: 1: lemon-clang: not found
[9/226] Compiling C object subprojects/lai/liblai.a.p/core_os_methods.c.o
FAILED: subprojects/lai/liblai.a.p/core_os_methods.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_os_methods.c.o -MF subprojects/lai/liblai.a.p/core_os_methods.c.o.d -o subprojects/lai/liblai.a.p/core_os_methods.c.o -c ../subprojects/lai/core/os_methods.c
/bin/sh: 1: lemon-clang: not found
[10/226] Compiling C object subprojects/lai/liblai.a.p/core_variable.c.o
FAILED: subprojects/lai/liblai.a.p/core_variable.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_variable.c.o -MF subprojects/lai/liblai.a.p/core_variable.c.o.d -o subprojects/lai/liblai.a.p/core_variable.c.o -c ../subprojects/lai/core/variable.c
/bin/sh: 1: lemon-clang: not found
[11/226] Compiling C object subprojects/lai/liblai.a.p/core_vsnprintf.c.o
FAILED: subprojects/lai/liblai.a.p/core_vsnprintf.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/core_vsnprintf.c.o -MF subprojects/lai/liblai.a.p/core_vsnprintf.c.o.d -o subprojects/lai/liblai.a.p/core_vsnprintf.c.o -c ../subprojects/lai/core/vsnprintf.c
/bin/sh: 1: lemon-clang: not found
[12/226] Compiling C object subprojects/lai/liblai.a.p/helpers_pc-bios.c.o
FAILED: subprojects/lai/liblai.a.p/helpers_pc-bios.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/helpers_pc-bios.c.o -MF subprojects/lai/liblai.a.p/helpers_pc-bios.c.o.d -o subprojects/lai/liblai.a.p/helpers_pc-bios.c.o -c ../subprojects/lai/helpers/pc-bios.c
/bin/sh: 1: lemon-clang: not found
[13/226] Compiling C object subprojects/lai/liblai.a.p/helpers_pci.c.o
FAILED: subprojects/lai/liblai.a.p/helpers_pci.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/helpers_pci.c.o -MF subprojects/lai/liblai.a.p/helpers_pci.c.o.d -o subprojects/lai/liblai.a.p/helpers_pci.c.o -c ../subprojects/lai/helpers/pci.c
/bin/sh: 1: lemon-clang: not found
[14/226] Compiling C object subprojects/lai/liblai.a.p/helpers_resource.c.o
FAILED: subprojects/lai/liblai.a.p/helpers_resource.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/helpers_resource.c.o -MF subprojects/lai/liblai.a.p/helpers_resource.c.o.d -o subprojects/lai/liblai.a.p/helpers_resource.c.o -c ../subprojects/lai/helpers/resource.c
/bin/sh: 1: lemon-clang: not found
[15/226] Compiling C object subprojects/lai/liblai.a.p/helpers_sci.c.o
FAILED: subprojects/lai/liblai.a.p/helpers_sci.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/helpers_sci.c.o -MF subprojects/lai/liblai.a.p/helpers_sci.c.o.d -o subprojects/lai/liblai.a.p/helpers_sci.c.o -c ../subprojects/lai/helpers/sci.c
/bin/sh: 1: lemon-clang: not found
[16/226] Compiling C object subprojects/lai/liblai.a.p/helpers_pm.c.o
FAILED: subprojects/lai/liblai.a.p/helpers_pm.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/helpers_pm.c.o -MF subprojects/lai/liblai.a.p/helpers_pm.c.o.d -o subprojects/lai/liblai.a.p/helpers_pm.c.o -c ../subprojects/lai/helpers/pm.c
/bin/sh: 1: lemon-clang: not found
[17/226] Compiling C object subprojects/lai/liblai.a.p/drivers_ec.c.o
FAILED: subprojects/lai/liblai.a.p/drivers_ec.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/drivers_ec.c.o -MF subprojects/lai/liblai.a.p/drivers_ec.c.o.d -o subprojects/lai/liblai.a.p/drivers_ec.c.o -c ../subprojects/lai/drivers/ec.c
/bin/sh: 1: lemon-clang: not found
[18/226] Compiling C object subprojects/lai/liblai.a.p/drivers_timer.c.o
FAILED: subprojects/lai/liblai.a.p/drivers_timer.c.o 
lemon-clang -Isubprojects/lai/liblai.a.p -Isubprojects/lai -I../subprojects/lai -I../subprojects/lai/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -g -MD -MQ subprojects/lai/liblai.a.p/drivers_timer.c.o -MF subprojects/lai/liblai.a.p/drivers_timer.c.o.d -o subprojects/lai/liblai.a.p/drivers_timer.c.o -c ../subprojects/lai/drivers/timer.c
/bin/sh: 1: lemon-clang: not found
ninja: build stopped: subcommand failed.

**Comment by fido2020** [comment]
This is because lemon-clang is not in the PATH. It might be better to generate the meson crossfile in configure.sh, with absolute paths.
