### ISSUE TITLE
building LemonOS

### ISSUE THREAD

**Issue by krishpranav** [LemonOSProject/LemonOS#25]
hi @LemonOS project team is there any way to build LemonOS in macOS??

**Comment by fido2020** [comment]
Hi!

Unfortunately I do not own any macs so whilst it will probably compile, I highly doubt the disk image creation will work. You are more than welcome to test and fix this and submit a PR.

**Comment by krishpranav** [comment]
thanks @fido2020 for your reply!!! :)
