### ISSUE TITLE
Ship a premade image

### ISSUE THREAD

**Issue by pivxta** [LemonOSProject/LemonOS#3]
It would be cool for people that want to test the project, but don't want to build everything from scratch. Also, I tried to build it but I got a lot of unexpected problems (Compiler errors (with nyancat and lemond), Script permission problems (fixed with "chmod +x"), Non-existent headers (with lemond), etc.) and I'm pretty sure I installed all of the required dependencies for my distribution and followed exactly the build instructions.

**Comment by fido2020** [comment]
Thanks for letting me know, it has been a while since I have done a clean build and I will make sure to fix those issues, also when I get the chance I will upload a premade image.

**Comment by fido2020** [comment]
[I have added a premade image here](https://github.com/fido2020/Lemon-OS/releases/tag/0.2.0)
The compiler errors have also been fixed, thanks for letting me know about those.

**Comment by pivxta** [comment]
Thank you for fixing them!
