### ISSUE TITLE
OS bootable image?

### ISSUE THREAD

**Issue by marshallovski** [LemonOSProject/LemonOS#36]
Can someone create a image (like iso) to boot on real hardware?

**Comment by fido2020** [comment]
Hi, as shown in the README, go to [the github workflows page](https://github.com/LemonOSProject/LemonOS/actions/workflows/ci.yml?query=is%3Asuccess+branch%3Amaster), click on the latest run, and then a .img (raw harddisk image) can be downloaded from 'Artifacts'
