### ISSUE TITLE
Can i create a LemonOS app from another platform?

### ISSUE THREAD

**Issue by ilgrandeanonimo** [LemonOSProject/LemonOS#47]
Can i create a LemonOS app from another platform?

Whic of this can i use?
- macOS 13 Ventura arm64
- macOS 13 Ventura x86_64
- Ubuntu 22.04 arm64

PS If needed i can use all arm64 linux distros.

**Comment by fido2020** [comment]
I've never tested building under ARM and building under macOS is also untested, you can try building the system as per the build instructions but I can't say how many issues you will run into.
