### ISSUE TITLE
GCC Build Fail

### ISSUE THREAD

**Issue by pdpdds** [LemonOSProject/LemonOS#5]
./buildtoolchain.sh build

LEMON_SYSROOT or TOOLCHAIN_PREFIX not set, continuing will use defaults:\nTOOLCHAIN_PREFIX: /root/.local/share/lemon\nLEMON_SYSROOT: /root/.local/share/lemon/sysroot
.......

Build proceeds. but last result is
cp: '/root/.local/share/lemon/x86_64-lemon/lib/libgcc_s.so' There are no such files or directories

but i can confirm libgcc_s.so file generated.

can you resolve this?

**Comment by fido2020** [comment]
libgcc_s.so should be a symlink, what does it point to?

**Comment by pdpdds** [comment]
root@darkx-VirtualBox:~# cd /root/.local/share/lemon/x86_64-lemon/lib/
root@darkx-VirtualBox:~/.local/share/lemon/x86_64-lemon/lib# ls
libgcc_s.so
root@darkx-VirtualBox:~/.local/share/lemon/x86_64-lemon/lib#

**Comment by fido2020** [comment]
Try `readlink -f ~/.local/share/lemon/x86_64-lemon/lib/libgcc_s.so`

**Comment by pdpdds** [comment]
root@darkx-VirtualBox:~/.local/share/lemon/x86_64-lemon/lib# readlink -f ~/.local/share/lemon/x86_64-lemon/lib/libgcc_s.so
/root/.local/share/lemon/x86_64-lemon/lib/libgcc_s.so.1
root@darkx-VirtualBox:~/.local/share/lemon/x86_64-lemon/lib#

**Comment by fido2020** [comment]
ok so libgcc_s.so.1 does not exist, try `find ~/.local/share/lemon -name libgcc_s.so.1`, if that does not work are you sure the build succeeded?

**Comment by pdpdds** [comment]
only fact i know is that build was processed. and after 10-20 miniutes, last error message was "cp: '/root/.local/share/lemon/x86_64-lemon/lib/libgcc_s.so' There are no such files or directories". i will try build again and i will look out whether error message exists. thanks.

**Comment by pdpdds** [comment]
i found error message as you say.

/home/Lemon-OS/Toolchain/build-gcc/./gcc/collect-ld: 106: exec: -shared: not found
collect2: error: ld returned 127 exit status
Makefile:989: recipe for target 'libgcc_s.so' failed
make[1]: *** [libgcc_s.so] Error 1

What should I do?

**Comment by pdpdds** [comment]
I tried build in WSL2 finally.
below is error message.
......
/home/darkx/.local/share/lemon/x86_64-lemon/bin/ar  rc libgcov.a $objects
/home/darkx/.local/share/lemon/x86_64-lemon/bin/ranlib libgcov.a
/home/darkx/.local/share/lemon/x86_64-lemon/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:994: libgcc_s.so] Error 1
.....

i think i have proceed as build instruction.

**Comment by fido2020** [comment]
Sorry it has been over a month now, however this has been because I was in the middle of switching to an LLVM/Clang toolchain and now Lemon can be [built with docker ](https://github.com/fido2020/Lemon-OS/wiki/Building-Lemon-OS-with-Docker) which should make building much quicker and easier, so I am going to close the issue now.
