### ISSUE TITLE
is lemon a linux OS?

### ISSUE THREAD

**Issue by JonnycatMeow** [LemonOSProject/LemonOS#55]
is it?

**Comment by ilgrandeanonimo** [comment]
No, it is an independent os

**Comment by JonnycatMeow** [comment]
i have 2 questions 1. but for the kernel is it linux or macos or is it dependent? 2. for the static and the shared library's will there be a .a for static and a .so for shared or will it be diffrent?

**Comment by ilgrandeanonimo** [comment]
1. Indipendent
2. IDK

**Comment by JonnycatMeow** [comment]
oh ok thank you
