### ISSUE TITLE
LemonOS crashes on VirtualBox

### ISSUE THREAD

**Issue by Onmp314** [LemonOSProject/LemonOS#6]
Hi,

I would like to report a bug that prevents LemonOS from being launching in VirtualBox.

Logs: [VBox.log](https://github.com/fido2020/Lemon-OS/files/5540421/VBox.log)

**Comment by nexos-dev** [comment]
It looks to me like the problem is with the ATA driver in LemonOS. Try using a SATA drive in VirtualBox.

**Comment by Onmp314** [comment]
Thank you for solving the problem, so I will close issue.
