### ISSUE TITLE
git clone fail

### ISSUE THREAD

**Issue by pdpdds** [LemonOSProject/LemonOS#7]
git clone https://github.com/fido2020/Lemon-OS.git --recurse-submodules
......
Submodule path 'Applications/subprojects/LemonUtils': checked out '1b118e0e14b9ee3ce3e5fa3b7294450132aac7b2'
fatal: remote error: upload-pack: not our ref 06aedffc30dc97279306246a8f284876bde67371
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'LibC', but it did not contain 06aedffc30dc97279306246a8f284876bde67371. Direct fetching of that commit failed.

**Comment by fido2020** [comment]
Thanks for letting me know, the issue has now been resolved.
`Submodule path 'Applications/subprojects/LemonUtils': checked out '1b118e0e14b9ee3ce3e5fa3b7294450132aac7b2'
Submodule path 'LibC': checked out '06aedffc30dc97279306246a8f284876bde67371'`
