### ISSUE TITLE
docker install error

### ISSUE THREAD

**Issue by pdpdds** [LemonOSProject/LemonOS#8]
Scripts/docker-configure.sh

.......................
mlibc undefined

  Subprojects
    cxxshim: YES
      frigg: YES

Found ninja-1.9.0 at /usr/bin/ninja

ERROR: Clock skew detected. File /mnt/c/ubuntu/Lemon-OS/LibC/build/meson-private/coredata.dat has a time stamp 0.0942s in the future.

A full log can be found at /mnt/c/ubuntu/Lemon-OS/LibC/build/meson-logs/meson-log.txt
ninja -j12 -C LibC/build install
ninja: open build.ninja: No such file or directory
make: *** [Makefile:8: libc] Error 1

**Comment by fido2020** [comment]
Hmm that is definitely strange, try deleting LibC/build and rerunning the script

**Comment by pdpdds** [comment]
it seems to be wsl2 bug. i resolved it. thanks

**Comment by pdpdds** [comment]
but some error happen.

......
The Meson build system
Version: 0.56.0
Source dir: /mnt/c/ubuntu/Lemon-OS/LibLemon
Build dir: /mnt/c/ubuntu/Lemon-OS/LibLemon/build
Build type: cross build
Project name: LibLemon
Project version: undefined
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64

meson.build:3:0: ERROR: Neither a subproject directory nor a json.wrap file was found.

**Comment by fido2020** [comment]
Alright I just pushed a fix

**Comment by pdpdds** [comment]
kernel build error

......
The Meson build system
Version: 0.56.0
Source dir: /mnt/c/ubuntu/b/Lemon-OS/Kernel
Build dir: /mnt/c/ubuntu/b/Lemon-OS/Kernel/build
Build type: cross build
Project name: Lemon Kernel
Project version: undefined
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
C compiler for the build machine: cc (gcc 9.3.0 "cc (Alpine 9.3.0) 9.3.0")
C linker for the build machine: cc ld.bfd 2.34
Compiler for language cpp for the build machine not found.
C compiler for the host machine: lemon-clang (clang 11.0.0 "Lemon clang version 11.0.0 (https://github.com/fido2020/llvm-project.git 2e1bea1c2bf1c88824482f5d57e52b0233b23b00)")
C linker for the host machine: lemon-clang ld.bfd 2.32
C++ compiler for the host machine: lemon-clang++ (clang 11.0.0 "Lemon clang version 11.0.0 (https://github.com/fido2020/llvm-project.git 2e1bea1c2bf1c88824482f5d57e52b0233b23b00)")
C++ linker for the host machine: lemon-clang++ ld.bfd 2.32
Program nasm found: YES (/usr/bin/nasm)
Program bintoelf.sh found: YES (/mnt/c/ubuntu/b/Lemon-OS/Kernel/bintoelf.sh)

meson.build:38:0: ERROR: Subproject exists but has no meson.build file

maybe this line seems to be error.
lai = subproject('lai')

**Comment by fido2020** [comment]
Thanks, pushed another fix

**Comment by pdpdds** [comment]
Scripts/docker-configure.sh => PASS

but this command error.

./docker-make all

......
Scripts/buildinitrd.sh
cp: cannot stat '/home/darkx/.local/share/lemon/lib/x86_64-lemon/c++/lib*so*': No such file or directory
cp: cannot stat 'Applications/build/lsh.lef': No such file or directory
cp: cannot stat 'Applications/build/subprojects/LemonUtils/*.lef': No such file or directory
Scripts/build-nix/copytodisk.sh
qemu-nbd: Failed to open /dev/nbd0: No such file or directory
qemu-nbd: Disconnect client, due to: Failed to read request: Unexpected end-of-file before all bytes were read
Error: Could not stat device /dev/nbd0 - No such file or directory.
error mounting disk image
make: *** [Makefile.docker:27: disk] Error 1

**Comment by pdpdds** [comment]
anyway, kernel.sys build success. so i close this issue.
