### ISSUE TITLE
Please enable discussion

### ISSUE THREAD

**Issue by maifeeulasad** [LemonOSProject/LemonOS#9]
I've been following development of this project this beginning. And I really love this project. I commented on YouTube sometimes. But enabling discussing would be great. As this project is getting cooler day by day.

**Comment by fido2020** [comment]
Thanks!

I agree, it would be great to have a platform for discussion of the project. I am thinking potentially discord as it works well across platforms and is easy to set up and for people to join.

**Comment by maifeeulasad** [comment]
It is also possible in GitHub now a days. It's just in the row with issue, wiki etc. All you have to do is go to settings and enable.

And yeah discord sounds nice too.
